### PR TITLE
Fix svg size in firefox

### PR DESCRIPTION
**Pull request by i1group**
In some cases donutty looks bad in firefox (while it's ok in chrome and opera). This PR fixes it.

Before: https://nimb.ws/C0nPcb
After: https://nimb.ws/LPFGac

### CODE REVIEW

**Comment by simeydotme** [comment]
I'll get to this asap :)
Thanks, again, @i1group

**Comment by simeydotme** [comment]
Hi, @i1group  , I finally had a chance to get to this :)

Thanks for finding the issue with the width/height! 
I've cherry picked that commit and published a new version. But I wasn't happy with the unrelated `truth` commit as I don't see any need for that right now. 

Thanks! 

----

p.s. check out this sandbox with Donutty running under Svelte3 :)
https://codesandbox.io/s/donutty-test-o6dj3

**Comment by ivan-compucorp** [comment]
I think that `truth` update maybe useful if user will write the following:
`<div data-donutty circle="1" round="0">`

--
P.S. https://codesandbox.io/s/donutty-test-o6dj3 is not working: https://nimb.ws/7wUzag

**Comment by i1group** [comment]
I'm glad you did it :) thanks.
And I think that `truth` update maybe useful if user will write the following:
`<div data-donutty circle="1" round="0">`

--
P.S. https://codesandbox.io/s/donutty-test-o6dj3 is not working: https://nimb.ws/7wUzag

**Pull request closed without merging**
